title:            
tagline:          Site for some stuff.
description:      This site contains things.
#Comment out url when working locally to resolve base urls correctly
url: http://nikopartanen.github.io

# Owner/author information
owner:
  name:           Niko Partanen
  avatar:         avatar.png
  bio:            "Linguist"
  email:          nikotapiopartanen@gmail.com
  twitter:        nikopartanen        
  github:         nikopartanen       
  location:       "Freiburg im Breisgau, Germany"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Freiburg Research Group in Saami Studies
    url: http://www.skandinavistik.uni-freiburg.de/forschung/saami
    external: true
  - title: Niko Partanen
    url: https://www.facebook.com/niko.partanen.3
  - title: CV
    url: https://www.facebook.com/niko.partanen.3
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

scholar:
  style: assets/bibliography/mycslfile.csl
  locale: en
 
  sort_by: year
  order: descending
 
  source: /Users/niko/art/FReiburg/bibtex
  bibliography: FRibliography
  bibliography_template: bibtemplate
 
  replace_strings: true
 
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
 
  query: "@*"
